[package]
name = "identity-macros"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"