[package]
name = "identity-wasm"
version = "0.3.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Web Assembly bindings for the identity-rs crate."
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity", "wasm"]
homepage = "https://www.iota.org"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1" }
futures = { version = "0.3" }
js-sys = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4", default-features = false }
once_cell = "1.8.0"

[dependencies.tokio]
version = "1.7"
default-features = false
features = ["rt"]

[dependencies.identity]
version = "=0.3.0"
path = "../../identity"
default-features = false
features = ["comm", "wasm"]

[dependencies.libp2p]
git = "https://github.com/libp2p/rust-libp2p"
version = "0.39"
default-features = false
features = ["wasm-ext", "websocket", "wasm-ext-websocket"]

[dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
getrandom = { version = "0.2", features = ["js"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
